"""Test

Revision ID: 6acf0c40ff8f
Revises: 
Create Date: 2024-04-01 16:05:38.694569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acf0c40ff8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_column_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('column_name', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_column_metadata', schema='catalog')
    # ### end Alembic commands ###
