"""Add is_active column to Metadata

Revision ID: ea0a0769c35e
Revises: 6acf0c40ff8f
Create Date: 2024-04-01 16:21:51.627591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0a0769c35e'
down_revision = '6acf0c40ff8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_column_metadata', sa.Column('is_active', sa.Boolean(), nullable=False), schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_column_metadata', 'is_active', schema='catalog')
    # ### end Alembic commands ###
